### PR TITLE
Fix labintro README

### PR DESCRIPTION
**Pull request by jtudelag**
Fixes typos and updates info about scenarios.

### CODE REVIEW

**Comment by jtudelag** [comment]
Wait till I squash commits, sorry.

**Comment by jtudelag** [comment]
Fixes also some MarkDown format issues.

**Comment by jtudelag** [comment]
@makentenza @mjudeikis Please review ;)

**Review by makentenza — APPROVED** [review]
LGTM, thanks @jtudelag

**Pull request merged**
